---
# Source: jaafan/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jaafan
  labels:
    helm.sh/chart: jaafan-0.1.0
    app.kubernetes.io/name: jaafan
    app.kubernetes.io/instance: jaafan
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
