apiVersion: v1
kind: Service
metadata:
  name: {{ include "Deploy.fullname" . }}
  labels:
    {{- include "Deploy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: UDP
      name: udp-port
  selector:
    {{- include "Deploy.selectorLabels" . | nindent 4 }}
