# This file defines the build script for all supported aspnetcore images.
#   _DOCKER_NAMESPACE, the repository where to push the images.
#   _TAG, the tag to use for the published images.
steps:
# Build the generator for testing later.
# .NET Core 3.1.x
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', '${_DOCKER_NAMESPACE}/jaafan:3.1-${_TAG}','-f','Jaafan.Proxy/Dockerfile',
          '--no-cache','Jaafan.Proxy/' ]
  id: 'Build'
  waitFor: ['-']


#- name: "gcr.io/cloud-builders/gke-deploy"
#  args:
#  - run
#  - --filename=kubernetes-resource-file
#  - --image=${_DOCKER_NAMESPACE}/jaafan:{_TAG}
#  - --location=${_LOCATION}
#  - --cluster=${_CLUSTER}

  # Publish the images.
images:
  - '${_DOCKER_NAMESPACE}/jaafan:3.1-${_TAG}'
