# This file defines the build script for all supported aspnetcore images.
#   _DOCKER_NAMESPACE, the repository where to push the images.
#   _TAG, the tag to use for the published images.
steps:
# Build the generator for testing later.
# .NET Core 3.1.x
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', '${_DOCKER_NAMESPACE}/application.serviceproxy:3.1-${_TAG}','-f','Application.ServiceProxy/Dockerfile',
          '--no-cache','Application.ServiceProxy/' ]
  id: 'Build'
  waitFor: ['-']

  # Publish the images.
images:
  - '${_DOCKER_NAMESPACE}/application.serviceproxy:3.1-${_TAG}'
